services:
  - type: web
    name: blattkids
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.x
      - key: PORT
        value: 3000
